name: "viarail_project"
version: "1.0"
config-version: 2

profile: "viarail_profile"

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  viarail_project:
    core:
      materialized: incremental
    intermediate:
      materialized: table
    mart:
      materialized: view
vars:
  gcp_project_id: elt-viarail
